### ISSUE TITLE
贴吧仍需选择跳转或Safari

### ISSUE THREAD

**Issue by AlanDinkle** [shenruisi/Stay#10]
例如搜索“onedrive没有释放空间贴吧”
随便点击一个贴吧都会出现如图所示的界面，如红框和黄框所示，正常情况如图二。![image](https://user-images.githubusercontent.com/68946359/143176797-276bbffb-81bf-4bf2-b9a2-230a5d0d1902.jpeg)![image](https://user-images.githubusercontent.com/68946359/143176837-fc9b057c-3f87-48ed-87eb-5664d412b83b.png)

**Comment by shenruisi** [comment]
Fixed with #15
