### ISSUE TITLE
csdn会跳转

### ISSUE THREAD

**Issue by KangMz** [shenruisi/Stay#12]
1.在安装了csdn客户端的情况下，点击链接会跳转(同类型的 某100扩展 也是会跳)
2.此扩展似乎只能作用在百度的搜索页面下，其他的搜索引擎就会失效，全都会跳转。(这种情况在 某look浏览器 下也一样会出现)

btw:要说防跳转的话，感觉夸克做的好，几乎是100%防跳转了。很好奇夸克是怎么做到的。。难道也是用js？？

**Comment by shenruisi** [comment]
> 1.在安装了csdn客户端的情况下，点击链接会跳转(同类型的 某100扩展 也是会跳) 2.此扩展似乎只能作用在百度的搜索页面下，其他的搜索引擎就会失效，全都会跳转。(这种情况在 某look浏览器 下也一样会出现)
> 
> btw:要说防跳转的话，感觉夸克做的好，几乎是100%防跳转了。很好奇夸克是怎么做到的。。难道也是用js？？

csdn这些stay在后续的版本会继续兼容，夸克是自己做的浏览器，可以拦截scheme事件。

**Comment by KangMz** [comment]
太好了！！
更新了最新版本2.0.1 不会再出现偶尔跳转的情况发生了。
现在是点啥链接跳转啥，百家号跳百度，csdn跳csdn，知乎跳知乎。没一个不跳的，彻底解决了偶尔跳转的情况。
感谢作者！
