### ISSUE TITLE
没适配黑暗模式 iPad没适配也无法添加自定义脚本

### ISSUE THREAD

**Issue by njacknot** [shenruisi/Stay#16]
![image](https://user-images.githubusercontent.com/39458696/147350772-836f5a22-09f4-4a2a-bdbe-e8800b82a1ae.png)

**Comment by shenruisi** [comment]
@njacknot 添加的脚本可以发一下吗

**Comment by shenruisi** [comment]
Fixed on [release 2.0.2](https://github.com/shenruisi/Stay/releases/tag/v2.0.2)
