### ISSUE TITLE
It's impossible to use Stay on iPadOS

### ISSUE THREAD

**Issue by GamerPlayer888** [shenruisi/Stay#27]
This is how extension is look like **usually**:
![3CF95A74-F6F4-4CEF-8AA3-453B2D0A3B14](https://user-images.githubusercontent.com/66787796/149541264-38db3fcd-63f9-4e69-8e17-b98de745fce6.jpeg)
This is how extension is look like at **first launch Safari**:
![4AF5853A-26BA-41CE-BE22-3D05D7EBE269](https://user-images.githubusercontent.com/66787796/149541245-28aa0a00-7852-4580-b714-bff33c16fc5f.jpeg)
This is how extension is look like **in multitasking**:
![103D21A1-B384-4589-8F50-7FE09216F08A](https://user-images.githubusercontent.com/66787796/149541272-3d747d3c-6615-42fe-af68-0b91e55cccb2.jpeg)
An adaptation for iPadOS would be appreciated!

**Comment by shenruisi** [comment]
@GamerPlayer888 YES, this issue on iPadOS is being fixed.

**Comment by shenruisi** [comment]
Fixed on [release 2.0.2](https://github.com/shenruisi/Stay/releases/tag/v2.0.2)
