### ISSUE TITLE
[Embed Script Request]: 

### ISSUE THREAD

**Issue by bytxk** [shenruisi/Stay#32]
### Role

Collector

### Description

Sci-hub button 在文献页面上添加 Sci-hub 按钮，可以直接跳转到下载页面

### Script content

![D4870B80-D1E7-4C77-9567-64A36480E3A8](https://user-images.githubusercontent.com/62052872/151687951-8ea58656-340b-4bf0-871f-569b25117295.jpeg)

### Source page

https://greasyfork.org/scripts/370246-sci-hub-button/code/Sci-hub%20button.user.js

**Comment by shenruisi** [comment]
This script should run on the iPadOS. @bytxk
