### ISSUE TITLE
知乎脚本

### ISSUE THREAD

**Issue by AlanDinkle** [shenruisi/Stay#33]
https://greasyfork.org/zh-CN/scripts/407967-%E7%9F%A5%E4%B9%8E%E6%89%8B%E6%9C%BA%E7%BD%91%E9%A1%B5%E7%89%88%E6%94%B9%E8%BF%9B

另外建议能够支持导入js文件，新建脚本还要复制文本，好麻烦呀

**Comment by shenruisi** [comment]
Script is supported on version 2.0.3

**Comment by omnjpa27516** [comment]
借楼反馈一下，这个脚本一直用的好好的，但是今天更新完脚本就挂了。

删除脚本重装最新版（1.3.4），无效。
删除脚本重装之前能用的版本（1.3.2），无效。
卸载Stay重装，无效。

https://greasyfork.org/zh-CN/scripts/407967-%E7%9F%A5%E4%B9%8E%E6%89%8B%E6%9C%BA%E7%BD%91%E9%A1%B5%E7%89%88%E6%94%B9%E8%BF%9B/diff?v1=1064637&v2=1034008
两个版本对比，感觉不像是脚本方面的问题。

@shenruisi
