### ISSUE TITLE
百度贴吧依旧可以跳转

### ISSUE THREAD

**Issue by cyril-cheng** [shenruisi/Stay#4]
在safari里开了stay，也设置了允许拦截贴吧和百度，但是点开贴吧链接依旧直接跳转，都不带提示的，没装stay前好歹跳转的时候还有个弹窗提示。

**Comment by shenruisi** [comment]
是从百度点到贴吧的帖子吗

**Comment by cyril-cheng** [comment]
是啊，在safari里用百度搜索，点击结果里的百度贴吧的帖子，然后就跳转了。

**Comment by acerlb** [comment]
> 是啊，在safari里用百度搜索，点击结果里的百度贴吧的帖子，然后就跳转了。

这个是百度搜索的结果页拦截问题

**Comment by shenruisi** [comment]
Temporarily Close this issue, please try the [latest release](https://github.com/shenruisi/Stay/releases/tag/v2.0.2) @cyril-cheng
