### ISSUE TITLE
Google@PreventAppJump-0.0.1有bug

### ISSUE THREAD

**Issue by forgmissyou** [shenruisi/Stay#42]
Google搜索recaptcha.net，在脚本开启的情况下，搜索结果第一条为知乎专栏，第二条为Google开发网站。单击第二条，在新标签页打开的是知乎专栏；长按第二条，预览正确、再单击进入网站依然正确。关闭脚本，单击打开结果正确。

**Comment by shenruisi** [comment]
@forgmissyou  请升级下脚本 https://github.com/shenruisi/Stay-Offical-Userscript

**Comment by forgmissyou** [comment]
> @forgmissyou 请升级下脚本 https://github.com/shenruisi/Stay-Offical-Userscript

可以了，多谢，没注意到脚本不是最新的，全部更新了^_^
