### ISSUE TITLE
[Embed Script Request]: Bilibili-Evolved

### ISSUE THREAD

**Issue by SongzhouYang** [shenruisi/Stay#50]
### Role

Collector

### Description

Bilibili 增强脚本

### Script content

https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js

### Source page

https://github.com/the1812/Bilibili-Evolved

**Comment by shenruisi** [comment]
Supported on version 2.3.1
